name: "Technical Task (SoftDesk Support)"
description: "Tâche technique (CI, sécurité, perf, refacto, outillage)."
title: "[TECH-XX] <titre court>"
labels: ["type:tech"]
body:
  - type: dropdown
    id: epic
    attributes:
      label: Epic (si applicable)
      options:
        - "EPIC 1 – Authentification & comptes"
        - "EPIC 2 – Projets & membership (contributors)"
        - "EPIC 3 – Issues"
        - "EPIC 4 – Commentaires"
        - "EPIC 5 – Sécurité, conformité, optimisation & CI"
    validations:
      required: false

  - type: input
    id: tech_id
    attributes:
      label: Identifiant (TECH-XX)
      description: "Ex: TECH-A, TECH-B… (utile pour dépendances / tracking)."
      placeholder: "TECH-A"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexte / Problème
      description: "Pourquoi cette tâche existe ? (contrainte école, bug, risque, dette tech…)"
      placeholder: "Ex: L’école exige 'OAuth2' → clarifier doc + implémentation retenue."
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: Objectif technique
      description: "Une phrase claire : résultat attendu."
      placeholder: "Ex: Aligner l’auth avec l’exigence 'OAuth2' (doc + endpoints token + Bearer)."
    validations:
      required: true

  - type: textarea
    id: endpoints
    attributes:
      label: Endpoints / Surface API (si pertinent)
      description: "Liste rapide des endpoints concernés (sinon laisser vide)."
      placeholder: |
        - POST /api/v1/auth/login/
        - POST /api/v1/auth/refresh/
        - GET /api/v1/users/me/
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Portée / fichiers impactés
      placeholder: |
        - config/settings.py
        - config/urls.py
        - apps/users/...
        - postman/...
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Critères d’acceptation
      description: "Checklist vérifiable. Garde 3–7 points max (supprime ce qui ne s’applique pas)."
      value: |
        - [ ] Le comportement attendu est vérifiable (commande / appel API / preuve).
        - [ ] Tests ajoutés ou mis à jour et **passent** (pytest).
        - [ ] Lint/format **OK** (ruff).
        - [ ] Postman (collection/env) mis à jour si la surface API a changé.
        - [ ] README / doc mise à jour si nécessaire.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options: ["P0", "P1", "P2"]
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Taille (Sizing)
      options:
        - "XS (0.5 ½j)"
        - "S (1 ½j)"
        - "M (2 ½j)"
        - "L (4 ½j)"
        - "XL (6 ½j)"
    validations:
      required: true

  - type: input
    id: estimate_half_days
    attributes:
      label: Estimation (½j)
      placeholder: "1"
    validations:
      required: true

  - type: input
    id: dependencies
    attributes:
      label: Dépendances (optionnel)
      description: "IDs bloquants (USxx, TECH-xx)."
      placeholder: "US02, TECH-A"
    validations:
      required: false
